name: Datasketches-Java Manual Coverage Report

on:
    workflow_dispatch:

env:
    MAVEN_OPTS: -Xmx4g -Xms1g # for JVM

jobs:
    build:
        name: Build, Test, Coverage
        runs-on: ${{matrix.os}}
        strategy:
          fail-fast: false
          matrix:
            jdk: [ 8 ]
            os: [ ubuntu-latest ]
            include:
#              - os: windows-latest
#                skip_javadoc: "`-Dmaven`.javadoc`.skip=true"
#                skip_gpg: "`-Dgpg`.skip=true"
              - os: ubuntu-latest
                skip_javadoc: -Dmaven.javadoc.skip=true
                skip_gpg: -Dgpg.skip=true
#              - os: macos-latest
#                skip_javadoc: -Dmaven.javadoc.skip=true
#                skip_gpg: -Dgpg.skip=true

        env:
          JDK_VERSION: ${{ matrix.jdk }}

        steps:
        - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
          uses: actions/checkout@v3
          with:
              persist-credentials: false

        - name: Cache local Maven repository
          uses: actions/cache@v3
          with:
              path: ~/.m2/repository
              key: build-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
              restore-keys: build-${{ runner.os }}-maven-

        - name: Install Matrix JDK
          uses: actions/setup-java@v3
          with:
              java-version: ${{ matrix.jdk }}
              distribution: 'temurin'
              java-package: jdk
              architecture: x64 # options: x86, x64, armv7, aarch64, ppc64le
              # cache #option

        - name: Echo Java Version
          run: >
              java -version

        - name: Test, Package, Verify, Coverage Report
          if: ${{ matrix.jdk == 8 && success() }}
          run: >
              # Lifecycle: validate, compile, test, package, verify, install, deploy
              # Coverage reports are available after the verify phase
              # -B batch mode, -V show Version without stoppping, -q quiet, only show errors
              mvn verify coveralls:report -B
              -DrepoToken=${{secrets.coveralls_token}}
              ${{matrix.os.skip_javadoc}}
              ${{matrix.os.skip_gpg}}
